apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
    role: master
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - image: k8s.gcr.io/redis:e2e
        name: redis
        ports:
        - name: redis-server
          containerPort: 6379
