apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    role: replica
  name: redis-replica
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: replica

